Repository apache/openwhisk-website, pull requests merged in 2018-08, with the labels that each got.

#278 updating ruby version
  Gemfile
Labels: review

#283 adding comments
  Gemfile
  _scss/_base.scss
Labels: review

#277 updates for index and layout on large sizes
  _includes/index/index.js
  _layouts/community.html
  _layouts/documentation.html
  _layouts/downloads.html
  _scss/_base.scss
  _scss/_skin.scss
  _scss/_tablet.scss
  _scss/_variables.scss
  images/apache-openwhisk-test.png
  images/elements/arrow-down-12px.png
  images/elements/arrow-down.svg
  images/elements/arrow-right-12px.png
  images/elements/arrow-right.svg
Labels: review

#285 adding scripts/manifest
  code/Hello.java
  code/hello-with-params.js
  code/hello.go
  code/hello.js
  code/hello.php
  code/hello.py
  code/manifest-for-helloJS-1.yaml
  code/manifest-for-helloJS-2.yaml
  code/manifest-for-helloPhp-1.yaml
  code/manifest-for-helloPhp-2.yaml
  code/manifest-for-helloPy-1.yaml
  code/manifest-for-helloPy-2.yaml
Labels: review

#287 Fix terminal style and add code syntax highlighting support
  _scss/_base.scss
  _scss/_highlite-syntax-colors.scss
  _scss/_skin.scss
  _scss/_variables.scss
  css/highlite-syntax-colors.css
  css/main.scss
Labels: review

#289 an attempt to download latest css
  _layouts/default.html
  css/main-v1.scss
Labels: review

#288 Importing code from scripts instead of hardcoding in html file
  _layouts/documentation.html
  _plugins/remote_file_content.rb
  _plugins/remote_markdown.rb
Labels: review

#290 tweak css color for syntax highlite of name constants
  _scss/_highlite-syntax-colors.scss
Labels: review

#291 ADjust colors for yaml and bash; add bash highlighting
  _layouts/documentation.html
  _scss/_highlite-syntax-colors.scss
  _scss/_skin.scss
Labels: review

#296 adjust header flow layout margins to match content
  _layouts/documentation.html
  _scss/_base.scss
  _scss/_desktop.scss
  _scss/_tablet.scss
  _scss/_variables.scss
Labels: review

#299 Adding GitHub repo structure
  _layouts/documentation.html
  _scss/_base.scss
  _scss/_variables.scss
Labels: review

#303 Fix slider plugin file
  _plugins/ideal_image_slider.rb
Labels: change, enhancement

#308 replacing remotefile with include
  _includes/code/Hello.java
  _includes/code/hello-with-params.js
  _includes/code/hello.go
  _includes/code/hello.js
  _includes/code/hello.php
  _includes/code/hello.py
  _includes/code/manifest-for-helloJS-1.yaml
  _includes/code/manifest-for-helloJS-2.yaml
  _includes/code/manifest-for-helloPhp-1.yaml
  _includes/code/manifest-for-helloPhp-2.yaml
  _includes/code/manifest-for-helloPy-1.yaml
  _includes/code/manifest-for-helloPy-2.yaml
  _layouts/documentation.html
Labels: review

#307 Add ASF required links and legal text to footer
  _includes/partial/site-footer.html
  _layouts/home.html
  _scss/_base.scss
  _scss/_desktop.scss
  _scss/_header.scss
  _scss/_skin.scss
  _scss/_tablet.scss
  _scss/_terminal.scss
  _scss/_variables.scss
Labels: content, documentation, enhancement, review

#310 Adjust header logo size and height + minor fixes to docs page
  _layouts/documentation.html
  _scss/_base.scss
  _scss/_desktop.scss
  _scss/_header.scss
  _scss/_tablet.scss
  _scss/_variables.scss
  images/apache-openwhisk.png
Labels: review

#313 Adding FAQ back with most relevant and obvious questions
  _includes/partial/faq.html
  _layouts/community.html
  _layouts/documentation.html
Labels: review

#318 Create updated package integrations illustration for home page
  _layouts/community.html
  _layouts/home.html
  _scss/_base.scss
  _scss/_variables.scss
  images/elements/alarm-clock.png
  images/elements/crescent.png
  images/elements/drawing-8-sided-cog.svg
  images/elements/drawing-cog-lt-aquamarine.png
  images/elements/drawing-cog-med-gray.png
  images/elements/events-average.png
  images/elements/events-cold.png
  images/elements/events-hot.png
  images/elements/function-of-x-notation.png
  images/elements/openwhisk-abstract-component.svg
  images/elements/rocket-launch.png
  images/icons/apache-openwhisk.svg
  images/icons/cloud-plus.svg
  images/icons/database.png
  images/icons/database2.svg
  images/icons/package.svg
  images/icons/raincloud.svg
  images/icons/sun-cloud.svg
  images/icons/weather.svg
  images/illustrations/OW-Integrations.png
  images/illustrations/OW-integrations.svg
Labels: design, documentation, review

#319 Adjust integrations image and text to have compatible heights
  _layouts/home.html
  images/illustrations/OW-Integrations.png
Labels: review

#322 Fix missing ending statement in php example
  _includes/code/hello.php
Labels: review

#325 Add Apache current events as well as provide project feature logo.
  _includes/partial/site-footer.html
  _layouts/community.html
  images/events/current-event-234x60.png
  images/logo/apache-openwhisk-vertical-212px.png
  images/logo/apache-openwhisk-vertical.svg
Labels: documentation, enhancement, review

#323 Fix list nesting
  _includes/partial/faq.html
  _layouts/documentation.html
Labels: review
